#![no_std]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

use core::panic::PanicInfo;

// Include the C bindings generated by build.rs
include!(concat!(env!("OUT_DIR"), "/c_bindings.rs"));

/// This struct will be automatically exported to rust_interface.h
#[repr(C)]
pub struct RustMetadata {
    pub safety_score: u32,
    pub is_verified: bool,
}

#[no_mangle]
pub extern "C" fn rust_verify_pmm(total_frames: u32, free_frames: u32) -> bool {
    // We can now call C functions directly if they were in the bindgen headers!
    // Example: unsafe { some_c_kernel_function(); }
    
    if free_frames > total_frames {
        return false;
    }
    true
}

#[panic_handler]
fn panic(_info: &PanicInfo) -> ! {
    loop {}
}